### ISSUE TITLE
Upgrade WP Sage Core Commenting - Part One - Sorting

### ISSUE THREAD

**Issue by juhewitt** [bcgov/citizen-engagement-web-toolkit#5]
# Sorting
## Background
We are looking to build upon the default core SAGE framework/WP OOTB commenting system.  As fans of the plug and play model, we are trying to accomplish this in a modular way for obvious reasons.  Through UX testing, our audience has identified three short comings to overcome: sorting, filtering and sequential loading.  This ticket, we are going to focus on Sorting.

### Story
I want to be able to sort blog comments by date and number of replies so that I can find information more easily to engage in consultations. 

## Acceptance Criteria
1. A user selects a sort by date toggle: 
  * the initial state is most recent.  
  * Toggle and the comments are returned by oldest.  
  * Toggle again and the sort and the comments are returned by most recent.
2. A user selects to sort by number of replies toggle, the initial state is default, with no sort applied at all. 
  * Toggle once and the comments are returned by the highest number of replies, 
  * toggle twice and the comments are returned by the least number of replies, 
  * and finally toggle three times and the comments are returned at the default.  
3.  Ideally, the solution will have AJAX response for UX.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines] (https://github.com/bcgov/citizen-engagement-web-toolkit/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page] (https://bcdevexchange.org/programs/Citizen%20Engagement%20Web%20Toolkit)  for more information on our work.

**Comment by SteveMHoward** [comment]
Hi I am Steve Howard and I am the technical contact. If you have questions, please post a comment here.

**Comment by coakenfold** [comment]
Am I correct in thinking this issue is related to enhancing Wordpress features and not the SAGE framework?

**Comment by SteveMHoward** [comment]
Correct. We use the Sage framework as our base for custom WordPress themes, but the specific issues that we have posted are about improving the base comment functionality. 

The solution does need to work within the Sage framework, so it has been included for reference.

**Comment by lmullane** [comment]
Q: What license is this project under?
A: Code received by Pull Request will be under Apache 2.0.

**Comment by coakenfold** [comment]
Does sorting by replies refer to how many replies a single comment has received?

For example, given the following:
- Comment A
-- 1st response to comment A
- Comment B
-- 1st response to comment B
-- 2nd response to comment B
-- 3rd response to comment B
- Comment C
- Comment D

"Toggle once and the comments are returned by the highest number of replies" would result in:
- Comment B
- Comment A
- Comment C
- Comment D

"toggle twice and the comments are returned by the least number of replies" would result in:
- Comment C
- Comment D
- Comment A
- Comment B

**Comment by SteveMHoward** [comment]
Yes it does.

Your example is bang on.

**Comment by lmullane** [comment]
Q: Should I let people know I am working on this issue?
A: It would be great if you would comment in this thread to let others know you intend to work on this issue.

**Comment by coakenfold** [comment]
I'd like to work on this issue. 

I've done some experiments/research and I think the sort by date is figured out. 

Made progress on sort by replies but still need to figure out a few issues.

**Comment by lmullane** [comment]
@coakenfold Thanks for letting us know.

**Comment by coakenfold** [comment]
How should sort by date work with nested comments? 

For example: the parent comment could be really old but the 5th comment in reply to the parent could be today's date.

- oldest comment
  - not so old comment
  - **comment made today**
- comment made yesterday
  - **another comment made today**

**Comment by SteveMHoward** [comment]
@coakenfold 

For this issue, please use the date of the parent comment for sorting by date.

So for your example, if sorted by newest:
- comment made yesterday
  - **another comment made today**
- oldest comment
  - not so old comment
  - **comment made today**

**Comment by coakenfold** [comment]
1) When submitting a pull request do we copy/paste the terms into the comment area of the PR?

2) Is the 'Email Address for Developer's PayPal Account' an address just for contacting the developer or does it have to be an email associated with the PayPal business account?

3) Do I include the PayPal pay by email at the top of the comment (with the terms)?

**Comment by lmullane** [comment]
@coakenfold Thanks for your questions. 
 
1)	Please submit the Terms in the comments section of the PR as an attachment; be sure to complete the information in the Acceptance section (i.e. legal name, email address).
2)	Yes, the email address should be associated with the PayPal business account.
3)	Yes please.

**Comment by SteveMHoward** [comment]
We have received a pull request for this issue: #10

**Comment by SteveMHoward** [comment]
We have accepted a pull request for this issue: #14

**Comment by lmullane** [comment]
Payment was made on Feb. 12th. Thanks again for your contribution, @coakenfold

**Comment by coakenfold** [comment]
Yes, I saw the payment on my end. Thanks so much!

Are there other Pay for Pull payment options being considered? The transaction fee from PayPal was around $30. If given the choice between waiting for a cheque to be mailed or getting paid $30 less, I'd choose the cheque.

**Comment by lmullane** [comment]
Good feedback, Chad. For the initial MVP we went with PayPal, but we are open to exploring other payment options. We just created a [user story in our backlog](https://github.com/BCDevExchange/BCDevExchange-app/issues/265) for this. Thank you.

**Comment by mark-a-wilson** [comment]
Hello @coakenfold. I'm a service designer working with the DevX to map out the Pay for Pull experience of both developers and public sector partners. Would you be available for a brief phone call so I could capture your experience so far? Please send me an email at Mark.Wilson@gov.bc.ca. Thanks!
