### ISSUE TITLE
Upgrade WP Sage Core Commenting - Part Two - Filtering

### ISSUE THREAD

**Issue by juhewitt** [bcgov/citizen-engagement-web-toolkit#6]
# Filtering
## Background
We are looking to build upon the default core SAGE framework/WP OOTB commenting system.  As fans of the plug and play model, we are trying to accomplish this in a modular way for obvious reasons.  Through UX testing, our audience has identified three short comings to overcome: sorting, filtering and sequential loading.  This ticket, we are going to focus on Filtering. 

### Story
I want to be able to filter comments by date or keywords so that I can find information more easily and participate in consultations more effectively.

## Acceptance Criteria
1. A user can filter information through a date field: 
  * by today's date
  * by week 
  * by month
2. A user can filter information through a search field, by:
  * keywords from within comment fields
  * keywords associated with author name
3. The results will return comments, in the same default format.
4. Ideally, the solution will perform these using AJAX calls.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines] (https://github.com/bcgov/citizen-engagement-web-toolkit/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page] (https://bcdevexchange.org/programs/Citizen%20Engagement%20Web%20Toolkit)  for more information on our work.

**Comment by SteveMHoward** [comment]
Hi I am Steve Howard and I am the technical contact. If you have questions, please post a comment here.

**Comment by lmullane** [comment]
Q: Should I let people know I am working on this issue?
A: It would be great if you would comment in this thread to let others know you intend to work on this issue.

**Comment by coakenfold** [comment]
I would like to work on this issue

**Comment by tempranova** [comment]
Hello! I'm working on this one as well. I have a sample up at http://tempranova.com/mortgage/2012/01/03/template-comments/ ... above the "__ responses to "Template:Comments", there are a couple of tabs ("Search by term", and "Filter by date").

The term searches through comment content and author name. Date searches either range as specified by user, or a preset time from the dropdown menu (dropdown menu takes precedence if range and dropdown are both selected with a value).

I have a couple of quick questions before I finish cleaning this up and push another PR:
- Is this manner of filtering time what you would like? Or would you prefer a dropdown with dates like "February 15-22, 2016", "June 2015", that kind of thing?
- Would you like to have search term and date filters combined, or separate as in the example?
- Do you want all found comments to load at once, regardless of the number returned?

I need to do a few small things, like validation and overall code cleanup, but let me know about these when you can and if this example matches what you were looking for.

**Comment by lmullane** [comment]
We have received a pull request for this issue: [#17](https://github.com/bcgov/citizen-engagement-web-toolkit/pull/17)

**Comment by SteveMHoward** [comment]
@tempranova 

Thanks for the example This is definitely on the right track.

To answer your questions:

1. Yes, this date filtering is good for the range.
2. I think it would be good to have the two filtering options in the same combined view. A user may want to view posts by "John" in the last 7 days.
3. It is fine to have all comments load at once for this issue. Eventually on our end we will need to make this issue work with the accepted solution in #7, but that is out of scope for this request. 
4. Just the comment author. 

Other than that, it would be nice to have some sort of "reset" button that clears the filters and displays all comments again. In the example site if you set the date range there doesn't seem to be any obvious way to undo the filter other than knowing the oldest post date, or by refreshing the page.

**Comment by tempranova** [comment]
Ok, those fixes and updates are made and pushed to my PR. I know I'm second in line anyways ... damn, shouldn't have asked;)

**Comment by juhewitt** [comment]
We have accepted two pull requests for this issue. Great work everyone!
