### ISSUE TITLE
Upgrade WP Sage Core Commenting - Part Three - Load More

### ISSUE THREAD

**Issue by juhewitt** [bcgov/citizen-engagement-web-toolkit#7]
# Load More
## Background
We are looking to build upon the default core SAGE framework/WP OOTB commenting system.  As fans of the plug and play model, we are trying to accomplish this in a modular way for obvious reasons.  Through UX testing, our audience has identified three short comings to overcome: sorting, filtering and sequential loading.  This ticket, we are going to focus on sequential loading. 

### Story
I want to be able to interact with groupings of comments dynamically so I can restrict the information presented to me for a more effective consultation experience.

## Acceptance Criteria
1. A user will read through a subset of comments on a page or post and:
  * select 'load more' to view the next subset of comments 
  * can continue to select 'load more' until all comments are present 
2. A user will read through a subset of replies within a thread on a page or post and:
  * select 'load more' to view the next subset of comments 
  * can continue to select 'load more' until all comments are present 
3. The admin of the blog can set the number of comments and replies within a set.
4. Ideally, the solution will perform these using AJAX calls.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines] (https://github.com/bcgov/citizen-engagement-web-toolkit/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page] (https://bcdevexchange.org/programs/Citizen%20Engagement%20Web%20Toolkit)  for more information on our work.

**Comment by SteveMHoward** [comment]
Hi I am Steve Howard and I am the technical contact. If you have questions, please post a comment here.

**Comment by boardom** [comment]
Unlikely that you have this at the moment, but in the future, having a docker image with a standard test/dev environment of the product built would probably go a long ways towards bringing more dev's onto the project quicker.

**Comment by summertriangle-dev** [comment]
> - The admin of the blog can set the number of comments and replies within a set.

What is a set? Is it the comments that are loaded from one "load more" action?

**Comment by lmullane** [comment]
Thanks for the suggestion, @boardom. We have been kicking the tires on Docker.

@summertriangle-dev I'm going to defer to @SteveMHoward to answer your question. He will be back online tomorrow.

**Comment by SteveMHoward** [comment]
@summertriangle-dev 

Yes, it is the number of comments by default, and loaded by one "load more" action.

So if the admin sets the "set length" to be 10, initially a max of 10 comments will be loaded, with a max of 10 replies per comment. If there are more than 10 comments, the "Load More" button will appear which will allow the user to dynamically load the next "set" of 10 comments, appended to the bottom of the existing comments.

**Comment by summertriangle-dev** [comment]
@SteveMHoward Okay.

And one more administrative question:

> For your pull request to be considered for payment, you must include a copy of the Terms completed with your information and a PayPal email link in the comments section of the of the pull request. Please read the Pay for Pull Terms.

Can the signed terms be submitted privately? Let's say I don't want anyone to know my name is "Lorenzo McLachlan".

**Comment by lmullane** [comment]
Thanks for your question, @summertriangele-dev. To be considered for payment you must include the Terms with your completed information as part of the Pull Request; there is no option to provide the Terms privately.

**Comment by lmullane** [comment]
Q: Can a developer submit more than one Pull Request?
A: Yes.

**Comment by lmullane** [comment]
Q: Should I let people know I am working on this issue?
A: It would be great if you would comment in this thread to let others know you intend to work on this issue.

**Comment by cazc** [comment]
Gonna work on this one.

**Comment by cazc** [comment]
Any thoughts on how should deeply-nested threads be handled? I'm thinking of restricting it to only loading top-level comments and immediate children initially, so you end up with something like:

- comment
  - reply  
    - **view replies**
  - reply  
    - **view replies**
  - reply  
    - **view replies**
  - reply  
    - **view replies**
  - reply  
    - **view replies**
  - above repeated N more times
  - **more**
- above repeated N more times
- **more**

I'm rolling my own loop using get_comments with a limit for this (`wp_list_comments` doesn't let me limit the number of children for each parent comment, unfortunately - I'm not doing it for fun). 

It looks something like 

```python
def my_get_comments(for_parent=None):
    top_levels = get_comments(...)
    for comment in top_levels:
        my_get_comments(for_parent=comment) # recursive!
```

It gets out of hand very quickly if N is high and there is a lot of nesting.

**Comment by SteveMHoward** [comment]
@cazc 

Your solution for deeply nested threads is good and would definitely work for us.

The custom comment function though, especially from a depth of 0, would probably not work. Our biggest worry would be about the lack of compatibility with the other two posted issues (#5 and #6) and with any other plugins that we currently use or may look to use in the future. These will usually depend on comments being posted in a WordPress way, and often use WordPress hooks, filters and the global $comment variable to modify parts of the comment box. 

Other options to tackle this may include:
- Creating a custom Walker Class object to navigate the comments tree in a more controlled fashion (https://codex.wordpress.org/Class_Reference/Walker), that would be called by the wp_list_comments function

- Overriding the wp_list_comments function within the theme (https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/comment-template.php#L1880)

- Some interesting combination between default comment depth and logic in the callback function

If you do find your self needing a custom way to retrieve comment data at some point, check out https://codex.wordpress.org/Function_Reference/get_comments. It allows the programmer to filter comments in a far more useful way, but it might be a challenge to integrate the data within the wp_list_comments structure.

We look forward to seeing what you come up with!

**Comment by coakenfold** [comment]
How does this issue differ from using the built-in Wordpress 'Older/Newer comments' buttons?

**Comment by SteveMHoward** [comment]
@coakenfold 

This would replace the limited "Older/Newer comments" functionality that ships with WordPress. 

With this issue:
- there is no pagination. All comments would be loaded on the same page dynamically by the user controlled "Load More" button.
- With the built-in solution, if a comment has a ton of replies it can completely take over the page space. This code would allow the user to "Load More" replies within a single comment chain if they want, or continue on to other comments without needing to first scroll past 50 replies.

**Comment by cazc** [comment]
How many comments do you expect to have as an upper limit on each post? Maybe 10000?

**Comment by SteveMHoward** [comment]
@cazc 

The most comments we have had in a single post has been in the hundreds, so an upper limit of 1000 should be fine.

**Comment by tempranova** [comment]
I've been working on this, I think I have a starting point sketched out. It's not totally up to submission standard yet, but ready for some review - should I put up a PR?

**Comment by tempranova** [comment]
Hello, just wondering if you would be willing to take a look and let me know what you think of what I've got going so far. Check out the repo at https://github.com/tempranova/citizen-engagement-web-toolkit/tree/master/code/bcgov-comment-theme/lib/custom/comment-load-more for an explanation, and a sample site online live at http://tempranova.com/mortgage/2012/01/03/template-comments/#comments.

This is using Sage and basic WP hooks, although I have a lot of cleaning up to do to get it up to the full WP and plugin standard. All the same please let me know when I should do a pull (if it should be done completely or OK now), and I will have most done in the next day or so.

**Comment by SteveMHoward** [comment]
@tempranova 

Thanks for your interest in this issue. The demo link that you have provided definitely meets the acceptance criteria. Please finish cleaning up and commenting the code and send us the finalized pull request.

**Comment by tempranova** [comment]
Thanks! https://github.com/bcgov/citizen-engagement-web-toolkit/pull/16

I did a PR with some cleaned up code - however it's not completely finished yet in terms of all testing and bugs. I am thinking you may want to try it out or give a few suggestions before I finalize everything. I note the following items to finish up still:
<ul>
    <li>Styling of comment boxes (right now they are squished in the left, missing some padding, etc)</li>
    <li>Test initial SQL querying (I will test loading with high numbers (1000+) of comments)</li>
    <li>Will add easy way to change text on "Newer Comment" button</li>
    <li>Options page possible if desired (commented out currently)</li>
</ul>

Please let me know if there's any more things you want to see - otherwise, I will have these wrapped up by tonight. I hope I'm still following protocol by doing my PR without it being 100% done;).

**Comment by SteveMHoward** [comment]
@tempranova 

Thanks for the Pull Request (#16). We will review this over the next week or so and let you know if it has been accepted.

As per the [TERMS.md](https://github.com/bcgov/citizen-engagement-web-toolkit/blob/master/TERMS.md) we review all pull requests in First In First Out order so if this request is not 100% complete, and another developer submits a completed pull request before your completed version, we would need to review their request next. 

Fortunately the terms also allow you to submit more than one request per issue so definitely send in a new pull request once you have completed everything.

**Comment by tempranova** [comment]
Got it. OK, I uploaded all the fixes I had planned to do. That PR I submitted (#16), should be good for your review and considered 100% done (at least prior to feedback).

Comments are tested with upwards of 200 comments on a single post, including a variety of replies and top-level comments.

**Comment by SteveMHoward** [comment]
We have accepted a pull request for this issue: #19
